### ISSUE TITLE
Reduce unbonding period in the next testnet

### ISSUE THREAD

**Issue by kwunyeung** [desmos-labs/morpheus#5]
Currently the unbonding period is set to the default 21-day. Undelegation and redelegation have to be locked in 21 days. We should reduce this to enable more rapid testing.

**Comment by kwunyeung** [comment]
This can be done after we have enabled `x/gov` and `x/upgrade` modules then change the parameter by governance.

**Comment by rmontagnin** [comment]
@kwunyeung the `x/gov` module is already enabled inside `morpheus-7001` and we should be able to change that parameter properly

**Comment by kwunyeung** [comment]
Great! Let's do that. The value should be the same as the `max_evidence_age`. We can set this as a new challenge for voting and upgrade.
